# Generated by Django 3.2.12 on 2022-03-15 09:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Формат ввода 7XXXXXXXXXX (X - цифра от 0 до 9)', regex='7[0-9]{10}')], verbose_name='Мобильный телефон')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('phone_number',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата начала рассылки')),
                ('text', models.TextField(max_length=255, verbose_name='Текст')),
                ('finish_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33, verbose_name='Оператор')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код оператора')),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33, unique=True, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки сообщения')),
                ('status', models.CharField(choices=[('Не отправлено', 'Не отправлено'), ('Отправляется', 'Отправляется'), ('Отправлено', 'Отправлено')], default='Не отправлено', max_length=33, verbose_name='Статус')),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_client', to='api.client', verbose_name='Клиент')),
                ('mailing', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_mailing', to='api.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('mailing',),
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='operators',
            field=models.ManyToManyField(blank=True, related_name='mailings_operator', to='api.Operator', verbose_name='Код оператора'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mailing_tags', to='api.Tag', verbose_name='Тэг'),
        ),
        migrations.AddField(
            model_name='client',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_operator', to='api.operator', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_tag', to='api.tag', verbose_name='Тэг'),
        ),
    ]
